# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on: [push]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Install dependencies
      run: go mod download

    - name: Create test-results directory
      run: mkdir test-results

    - name: Test
      run: go test -coverprofile=test-results/coverage.out -json -v ./... > test-results/unit-test.json

    - name: Generate coverage
      run: go tool cover -html=test-results/coverage.out -o test-results/coverage.html

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: Test results
        path: test-results/
